# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 05:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20170331_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Major')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bl_area', models.ManyToManyField(related_name='bl_area', to='core.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=3)),
                ('semester', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester', to='core.Calendar')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='letter',
            field=models.CharField(default=b'', max_length=1),
        ),
        migrations.AddField(
            model_name='crosslisting',
            name='letter',
            field=models.CharField(default=b'', max_length=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='semester',
            name='courses',
            field=models.ManyToManyField(to='core.Course'),
        ),
        migrations.AddField(
            model_name='record',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Course'),
        ),
        migrations.AddField(
            model_name='record',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='core.Profile'),
        ),
        migrations.AddField(
            model_name='preference',
            name='bl_courses',
            field=models.ManyToManyField(to='core.Course'),
        ),
        migrations.AddField(
            model_name='preference',
            name='bl_dept',
            field=models.ManyToManyField(related_name='bl_dept', to='core.Department'),
        ),
        migrations.AddField(
            model_name='preference',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='core.Profile'),
        ),
        migrations.AddField(
            model_name='preference',
            name='wl_area',
            field=models.ManyToManyField(related_name='wl_course', to='core.Area'),
        ),
        migrations.AddField(
            model_name='preference',
            name='wl_dept',
            field=models.ManyToManyField(related_name='wl_dept', to='core.Department'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='core.Profile'),
        ),
    ]
