# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-05 01:37
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20170331_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_accessed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_accessed'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bl_areas', models.ManyToManyField(related_name='bl_area', to='core.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2015)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_taken', models.PositiveSmallIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='core.Calendar')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=3)),
                ('semester', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester', to='core.Calendar')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='area',
            field=models.CharField(default=b'', max_length=3),
        ),
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.CharField(default=b'', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='letter',
            field=models.CharField(default=b'', max_length=1),
        ),
        migrations.AddField(
            model_name='crosslisting',
            name='letter',
            field=models.CharField(default=b'', max_length=1),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='short_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='crosslisting',
            name='number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='major',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='core.Degree'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='track',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='core.Major'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set([('number', 'department', 'letter')]),
        ),
        migrations.AlterUniqueTogether(
            name='crosslisting',
            unique_together=set([('course', 'number', 'department', 'letter')]),
        ),
        migrations.AddField(
            model_name='semester',
            name='courses',
            field=models.ManyToManyField(to='core.Course'),
        ),
        migrations.AddField(
            model_name='record',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Course'),
        ),
        migrations.AddField(
            model_name='record',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.Profile'),
        ),
        migrations.AddField(
            model_name='progress',
            name='courses_taken',
            field=models.ManyToManyField(to='core.Course'),
        ),
        migrations.AddField(
            model_name='progress',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='core.Requirement'),
        ),
        migrations.AddField(
            model_name='preference',
            name='bl_courses',
            field=models.ManyToManyField(to='core.Course'),
        ),
        migrations.AddField(
            model_name='preference',
            name='bl_depts',
            field=models.ManyToManyField(related_name='bl_dept', to='core.Department'),
        ),
        migrations.AddField(
            model_name='preference',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='core.Profile'),
        ),
        migrations.AddField(
            model_name='preference',
            name='wl_areas',
            field=models.ManyToManyField(related_name='wl_course', to='core.Area'),
        ),
        migrations.AddField(
            model_name='preference',
            name='wl_depts',
            field=models.ManyToManyField(related_name='wl_dept', to='core.Department'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Major'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='core.Profile'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='sandbox',
            field=models.ManyToManyField(to='core.Course'),
        ),
    ]
