# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 05:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170403_0533'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set([('number', 'department', 'letter')]),
        ),
        migrations.AlterUniqueTogether(
            name='crosslisting',
            unique_together=set([('course', 'number', 'department', 'letter')]),
        ),
    ]
