# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170403_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='short_name',
            field=models.CharField(max_length=50),
        ),
    ]
