# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-09 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170408_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='intrinsic_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
