# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170403_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='area',
            field=models.CharField(default=b'', max_length=3),
        ),
        migrations.AddField(
            model_name='course',
            name='course_id',
            field=models.CharField(default=b'', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='crosslisting',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
