# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-11 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together=set([('name', 'calendar')]),
        ),
    ]
