# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170403_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='name',
        ),
    ]
