# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-04 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_area_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_taken', models.PositiveSmallIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='preference',
            old_name='bl_area',
            new_name='bl_areas',
        ),
        migrations.RenameField(
            model_name='preference',
            old_name='bl_dept',
            new_name='bl_depts',
        ),
        migrations.RenameField(
            model_name='preference',
            old_name='wl_area',
            new_name='wl_areas',
        ),
        migrations.RenameField(
            model_name='preference',
            old_name='wl_dept',
            new_name='wl_depts',
        ),
        migrations.AddField(
            model_name='calendar',
            name='sandbox',
            field=models.ManyToManyField(to='core.Course'),
        ),
        migrations.AddField(
            model_name='progress',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='core.Calendar'),
        ),
        migrations.AddField(
            model_name='progress',
            name='courses_taken',
            field=models.ManyToManyField(to='core.Course'),
        ),
        migrations.AddField(
            model_name='progress',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='core.Requirement'),
        ),
    ]
