# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-12 04:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170412_0111'),
        ('core', '0006_auto_20170411_2346'),
    ]

    operations = [
    ]
