# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-17 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20170412_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='intrinsic_score',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='semester',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='core.Calendar'),
        ),
    ]
