# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-17 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170417_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Profile'),
        ),
    ]
