# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170417_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='term',
            field=models.PositiveSmallIntegerField(choices=[(1, b'Fall'), (2, b'Spring')], default=1),
        ),
    ]
