# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20170420_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='name',
            field=models.CharField(default=b'', max_length=25),
        ),
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
