# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 01:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20170420_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='name',
        ),
    ]
