# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_semester_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='user_completed',
            field=models.BooleanField(default=False),
        ),
    ]
