# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_progress_user_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='name',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
