# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_calendar_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='name',
            field=models.CharField(default=b'Default Calendar', max_length=50),
        ),
    ]
