# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-09 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20170502_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='use_flexibility',
            field=models.BooleanField(default=True),
        ),
    ]
